apiVersion: v1
kind: ServiceAccount
metadata:
  name: cis-redis-sa
  namespace: dev
  labels:
    app.kubernetes.io/name: cis-redis
    app.kubernetes.io/part-of: cis
    app.kubernetes.io/component: cache
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
