apiVersion: v1
kind: ServiceAccount
metadata:
  name: cis-admin-sa
  namespace: dev
  labels:
    app.kubernetes.io/name: cis-admin
    app.kubernetes.io/part-of: cis
    app.kubernetes.io/component: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
