apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cis
  namespace: argocd
  labels:
    app.kubernetes.io/name: cis
    app.kubernetes.io/part-of: cis
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:Dragnet-Solutions/cis.git
    targetRevision: k8s-release
    path: k8s-manifest
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
