apiVersion: v1
kind: ServiceAccount
metadata:
  name: cis-api-sa
  namespace: dev
  labels:
    app.kubernetes.io/name: cis-api
    app.kubernetes.io/part-of: cis
    app.kubernetes.io/component: api
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
